
package foot.soap.endpoints;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EndpointImplementationService", targetNamespace = "http://endpoints.soap.foot/", wsdlLocation = "http://localhost:8080/SoapEndFoot/services/EndpointImplementationPort?wsdl")
public class EndpointImplementationService
    extends Service
{

    private final static URL ENDPOINTIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENDPOINTIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName ENDPOINTIMPLEMENTATIONSERVICE_QNAME = new QName("http://endpoints.soap.foot/", "EndpointImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SoapEndFoot/services/EndpointImplementationPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENDPOINTIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        ENDPOINTIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public EndpointImplementationService() {
        super(__getWsdlLocation(), ENDPOINTIMPLEMENTATIONSERVICE_QNAME);
    }

    public EndpointImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENDPOINTIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public EndpointImplementationService(URL wsdlLocation) {
        super(wsdlLocation, ENDPOINTIMPLEMENTATIONSERVICE_QNAME);
    }

    public EndpointImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENDPOINTIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public EndpointImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndpointImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EndpointImplementation
     */
    @WebEndpoint(name = "EndpointImplementationPort")
    public EndpointImplementation getEndpointImplementationPort() {
        return super.getPort(new QName("http://endpoints.soap.foot/", "EndpointImplementationPort"), EndpointImplementation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndpointImplementation
     */
    @WebEndpoint(name = "EndpointImplementationPort")
    public EndpointImplementation getEndpointImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoints.soap.foot/", "EndpointImplementationPort"), EndpointImplementation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENDPOINTIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw ENDPOINTIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return ENDPOINTIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
