
package foot.soap.endpoints;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EndpointImplementation", targetNamespace = "http://endpoints.soap.foot/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EndpointImplementation {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<foot.soap.endpoints.Team>
     */
    @WebMethod(action = "urn:GetAllTeams")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllTeams", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetAllTeams")
    @ResponseWrapper(localName = "getAllTeamsResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetAllTeamsResponse")
    public List<Team> getAllTeams(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns foot.soap.endpoints.Players
     */
    @WebMethod(action = "urn:GetBestPlayer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBestPlayer", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetBestPlayer")
    @ResponseWrapper(localName = "getBestPlayerResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetBestPlayerResponse")
    public Players getBestPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:DeleteTeam")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTeam", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.DeleteTeam")
    @ResponseWrapper(localName = "deleteTeamResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.DeleteTeamResponse")
    public String deleteTeam(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns foot.soap.endpoints.Team
     */
    @WebMethod(action = "urn:CreateTeam")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTeam", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.CreateTeam")
    @ResponseWrapper(localName = "createTeamResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.CreateTeamResponse")
    public Team createTeam(
        @WebParam(name = "arg0", targetNamespace = "")
        Team arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns foot.soap.endpoints.League
     */
    @WebMethod(action = "urn:GetLeague")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLeague", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetLeague")
    @ResponseWrapper(localName = "getLeagueResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetLeagueResponse")
    public League getLeague(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns foot.soap.endpoints.Team
     */
    @WebMethod(action = "urn:UpdateTeam")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTeam", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.UpdateTeam")
    @ResponseWrapper(localName = "updateTeamResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.UpdateTeamResponse")
    public Team updateTeam(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Team arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns foot.soap.endpoints.Team
     */
    @WebMethod(action = "urn:GetTeamById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeamById", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetTeamById")
    @ResponseWrapper(localName = "getTeamByIdResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetTeamByIdResponse")
    public Team getTeamById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:DeleteLeague")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteLeague", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.DeleteLeague")
    @ResponseWrapper(localName = "deleteLeagueResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.DeleteLeagueResponse")
    public String deleteLeague(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns foot.soap.endpoints.League
     */
    @WebMethod(action = "urn:UpdateLeague")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateLeague", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.UpdateLeague")
    @ResponseWrapper(localName = "updateLeagueResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.UpdateLeagueResponse")
    public League updateLeague(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        League arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<foot.soap.endpoints.Players>
     */
    @WebMethod(action = "urn:GetBestPlayersLeague")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBestPlayersLeague", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetBestPlayersLeague")
    @ResponseWrapper(localName = "getBestPlayersLeagueResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetBestPlayersLeagueResponse")
    public List<Players> getBestPlayersLeague(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:DeletePlayer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePlayer", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.DeletePlayer")
    @ResponseWrapper(localName = "deletePlayerResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.DeletePlayerResponse")
    public String deletePlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns foot.soap.endpoints.League
     */
    @WebMethod(action = "urn:CreateLeague")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createLeague", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.CreateLeague")
    @ResponseWrapper(localName = "createLeagueResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.CreateLeagueResponse")
    public League createLeague(
        @WebParam(name = "arg0", targetNamespace = "")
        League arg0);

    /**
     * 
     * @return
     *     returns java.util.List<foot.soap.endpoints.League>
     */
    @WebMethod(action = "urn:GetAllLeagues")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLeagues", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetAllLeagues")
    @ResponseWrapper(localName = "getAllLeaguesResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.GetAllLeaguesResponse")
    public List<League> getAllLeagues();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns foot.soap.endpoints.Players
     */
    @WebMethod(action = "urn:AddPlayer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPlayer", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.AddPlayer")
    @ResponseWrapper(localName = "addPlayerResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.AddPlayerResponse")
    public Players addPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Players arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns foot.soap.endpoints.Players
     */
    @WebMethod(action = "urn:UpdatePlayer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePlayer", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.UpdatePlayer")
    @ResponseWrapper(localName = "updatePlayerResponse", targetNamespace = "http://endpoints.soap.foot/", className = "foot.soap.endpoints.UpdatePlayerResponse")
    public Players updatePlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Players arg2);

}
